fix: fix the issue where Serialization.init dynamically loads and catches Throwable, as java.lang.NoClassDefFoundError(is a Throwable) is thrown when the class does not exist.